#!/bin/bash
set -e

POLICIES=/usr/lib/firefox/distribution
mkdir -p ${POLICIES}
if [ ! -f ${POLICIES}/policies.json ]; then
    JQARGS=-n;
else
    JQARGS=${POLICIES}/policies.json;
fi
jq '.policies.ExtensionSettings["batch-signing@hia"] = {"installation_mode": "normal_installed", "install_url": "https://addons.mozilla.org/firefox/downloads/latest/hia-batch-signing/latest.xpi"}' ${JQARGS} > ${POLICIES}/policies.tmp
mv ${POLICIES}/policies.tmp ${POLICIES}/policies.json

#DEBHELPER#
